name: Auto Naukri Resume Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 7:30 AM IST
  workflow_dispatch:

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        # ✅ Fix: ignore error if symlink already exists
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true

    - name: Run script
      env:
        NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: |
        python naukri_update.py
