name: Auto Naukri Resume Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 7:30 AM IST
  workflow_dispatch:

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Google Chrome & ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip
        curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/google-linux-signing-keyring.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo ln -s /usr/bin/google-chrome /usr/bin/chrome || true
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true

    - name: Install Python dependencies
      run: |
        pip install selenium

    - name: Run the automation script
      env:
        NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: |
        python naukri_update.py
